version: "3.8"
services:
  users:
    container_name: users-svc
    build: ./users
    tty: true
    volumes:
      - ./users:/app
    networks:
      - app
    ports:
      - "8010:8080"
    depends_on:
      - db
  todos:
    container_name: todos-svc
    build: ./todos
    tty: true
    volumes:
      - ./todos:/app
    networks:
      - db
    ports:
      - "8011:8080"
    depends_on:
      - db
  db:
    container_name: mongo
    image: mongo:4.2.9
    restart: on-failure
    networks:
      - app

networks:
  app: