version: '3.8'
services:
  users:
    container_name: users-svc
    build: ./todo-user-svc
    tty: true
    volumes:
      - ./todo-user-svc:/app
    networks:
      - app
    ports:
      - '8010:8080'
    depends_on:
      - db
  db:
    container_name: mongo
    image: mongo:4.2.9
    restart: on-failure
    networks:
      - app

networks:
  app:
